input_dir: "/data/NCBR/rawdata/NCBR-410/assemblies"
result_dir: "/data/NCBR/projects/NCBR-410/brakerMake"
protein_file: "/data/OpenOmics/references/brakerMake/uniprot_sprot.fasta"
rna_dir: ""
rna_list: ""
